name: Use Packer To Build Custom Image

on:
  push:
    branches:
      - main

jobs:
  image_build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    strategy:
      matrix:
        cloud: [aws, gcp]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --omit=dev  # Install production dependencies only

      - name: Package Application
        run: tar -czf app.tar.gz index.js package.json tests/

      - name: Upload application artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-artifact
          path: app.tar.gz

      - name: Install Packer
        run: |
          if ! command -v packer &> /dev/null; then
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            sudo apt update && sudo apt install -y packer
          fi

      - name: Set up AWS Client Interface
        if: matrix.cloud == 'aws'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Google Cloud SDK
        if: matrix.cloud == 'gcp'
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_ACCESS_KEY }}
          export_default_credentials: true

      - name: Download application artifact
        uses: actions/download-artifact@v4
        with:
          name: application-artifact

      - name: Extract application artifact
        run: tar -xzf app.tar.gz -C .

      - name: Run packer init
        run: packer init machine-image.pkr.hcl

      - name: Build Packer Image
        run: |
          packer build \
          -var "cloud=${{ matrix.cloud }}" \
          -var "MYSQL_DB_NAME=${{ secrets.MYSQL_DB_NAME }}" \
          -var "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          machine-image.pkr.hcl
