name: Use Packer To Build Custom Image

on:
  push:
    branches:
      - main

jobs:
  image_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cloud: [aws, gcp]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --omit=dev  

      - name: Package Application
        run: tar -czf app.tar.gz index.js package.json tests/

      - name: Check if artifact file exists before uploading
        run: |
          if [ -f "app.tar.gz" ]; then
            echo "File app.tar.gz exists. Proceeding to upload."
          else
            echo "File app.tar.gz does not exist. Skipping upload."
            exit 0
          fi

      - name: Upload application artifact (if exists)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: application-artifact-${{ matrix.cloud }}
          path: app.tar.gz





      - name: Install Packer
        run: |
          if ! command -v packer &> /dev/null; then
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            sudo apt update && sudo apt install -y packer
          fi

      - name: Set up AWS Client Interface
        if: matrix.cloud == 'aws'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Google Cloud Auth
        if: matrix.cloud == 'gcp'
      
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        
      - name: Set up Cloud SDK
        if: matrix.cloud == 'gcp'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Check GCP Quotas
        if: matrix.cloud == 'gcp'
        run: |
          gcloud compute project-info describe --format="json" | jq '.quotas[] | select(.metric == "IN_USE_ADDRESSES")'
      

      - name: Download application artifact
        uses: actions/download-artifact@v4
        with:
          name: application-artifact-${{ matrix.cloud }}

      - name: Extract application artifact
        run: tar -xzf app.tar.gz -C .

      - name: Run packer init
        run: packer init machine-image.pkr.hcl

      - name: Build Packer Image
        if: matrix.cloud == 'aws'
        run: |
          packer build \
          -only=my-first-build.amazon-ebs.my-aws-ami \
          -var "cloud=${{ matrix.cloud }}" \
          -var "MYSQL_DB_NAME=${{ secrets.MYSQL_DB_NAME }}" \
          -var "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          machine-image.pkr.hcl
      

          
  
      - name: Build Packer Image for GCP
        if: matrix.cloud == 'gcp'
        run: |
          packer build \
          -only=my-first-build.googlecompute.my-gcp-image \
          -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var "MYSQL_DB_NAME=${{ secrets.MYSQL_DB_NAME }}" \
          -var "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          machine-image.pkr.hcl
      
  
  
