name: Use Packer To Build Custom Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  cli-test-artifact:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS Client Interface
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_DEV_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Install dependencies
        run: npm install --production  

      - name: Package backend API into a zip file
        run: zip -r backend-api.zip index.js package.json package-lock.json node_modules/ tests/ .env

      - name: Upload backend API artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-api
          path: backend-api.zip
          retention-days: 5

  image_build:
    needs: cli-test-artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cloud: [aws, gcp]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          sudo apt update && sudo apt install -y packer

      - name: Download backend API artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-api
          path: /tmp

      - name: Extract backend API
        run: unzip /tmp/backend-api.zip -d /tmp/backend-api

      - name: Set up AWS Client Interface
        if: matrix.cloud == 'aws'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Google Cloud SDK
        if: matrix.cloud == 'gcp'
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_DEV_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Run Packer Build
        run: |
          if [ "${{ matrix.cloud }}" == "aws" ]; then
            packer build machine-image.pkr.hcl
          else
            packer build machine-image.pkr.hcl
          fi
