name: Use Packer To Build Custom Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  cli-test-artifact:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS Client Interface
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_DEV_SERVICE_ACCOUNT_KEY  }}
          export_default_credentials: true
        
      

      - name: Install dependencies
        run: npm install  
        
      - name: Run tests
        run: npm test  
        

  image_build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    strategy:
      matrix:
        cloud: [aws, gcp]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          if ! command -v packer &> /dev/null; then
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            sudo apt update && sudo apt install -y packer
          fi

      - name: Set up AWS Client Interface
        if: matrix.cloud == 'aws'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_DEV_SERVICE_ACCOUNT_KEY  }}
          export_default_credentials: true

          
          
      - name: Run packer init
        run: packer init machine-image.pkr.hcl
        
          
      - name: Run packer fmt
        run: packer fmt -check -diff machine-image.pkr.hcl
          
      - name: Validate Packer Template
        run: |
          packer validate \
            -var "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" \
            -var "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" \
            -var "mysql_root_password=${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            machine-image.pkr.hcl

      - name: Build Packer Image
        run: |
          packer build \
            -var "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" \
            -var "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" \
            -var "mysql_root_password=${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            machine-image.pkr.hcl




          
     
