name: Packer CI

on:
  pull_request:
    branches:
      - main

jobs:
  packer-format-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          sudo apt update && sudo apt install -y packer

      - name: Run packer fmt
        run: |
          packer fmt -check -diff machine-image.pkr.hcl

      - name: Run packer validate
        run: |
          packer validate machine-image.pkr.hcl
